### ISSUE TITLE
问一下关于后端的问题

### ISSUE THREAD

**Issue by xuziang111** [fghrsh/live2d_demo#1]
对于后端的依赖只有加载模型吗，使用其他的功能不用依靠后端？

**Comment by fghrsh** [comment]
嗯，live2d_api 的后端的话是仅用于切换模型的.. 单个模型的话甚至不需要 API，一言 之类的功能由 一言 API 接口实现

**Comment by xuziang111** [comment]
@fghrsh 
好的，谢谢。
