### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by yyb1995** [fghrsh/live2d_demo#3]
你好，我想问下这里是不是当`live2d_settings.homePageUrl == 'auto'`时并没有进行赋值操作，只是做了判断？我觉得应该是`live2d_settings.homePageUrl = live2d_settings.homePageUrl == 'auto' ? window.location.protocol+'//'+window.location.hostname+'/' : live2d_settings.homePageUrl;`
https://github.com/fghrsh/live2d_demo/blob/cbd64c3f673363fc4018dc1b803f679c4382a40f/assets/waifu-tips.js#L154

**Comment by fghrsh** [comment]
唔.. 在 initModel() 前，应该已经 live2d_settings['homePageUrl'] = 'auto'; 了...

**Comment by yyb1995** [comment]
嗯就是这一步好像是当`live2d_settings.homePageUrl == 'auto'`时把它换成具体的地址，不知道我理解的对不对

**Comment by fghrsh** [comment]
嗯，当 `== 'auto'` 时，自动获取当前首页地址，否则为用户自定义的值

**Comment by yyb1995** [comment]
我用Chrome单步调试了一下，发现经过这句后`live2d_settings.homePageUrl`还是等于`'auto'`

**Comment by fghrsh** [comment]
![b4f3f8d44ecff5ee2330dc5e427c1aac.png](https://fp1.fghrsh.net/2019/06/13/b4f3f8d44ecff5ee2330dc5e427c1aac.png)

**Comment by fghrsh** [comment]
仔细看了下的确忘了赋值 ... 感谢提醒
