### ISSUE TITLE
还有一个小问题

### ISSUE THREAD

**Issue by yyb1995** [fghrsh/live2d_demo#4]
还有一个小问题，就是`result.waifu.hour_tips.t23-5`这些命名好像没有被正确识别成变量，我觉得是不是改成`result.waifu.hour_tips.t23_5`之类的才可以。
https://github.com/fghrsh/live2d_demo/blob/2ba297a2f21ddf9356f4ef47f431931c75604a61/assets/waifu-tips.js#L263-L272
https://github.com/fghrsh/live2d_demo/blob/2ba297a2f21ddf9356f4ef47f431931c75604a61/assets/waifu-tips.json#L8-L18

**Comment by fghrsh** [comment]
的确是... 感谢反馈
